<a href="https://colab.research.google.com/github/Jahnavim12/DA-ASSESSMENT/blob/main/DA_ASSESSMENT(67G5).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [92]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import re

In [93]:
df =pd.read_csv("/content/car_price_performance.csv")

In [94]:
df

        Brand  Price  Horsepower  Fuel Efficiency
0     Brand C  91942         382             15.3
1     Brand A  70075         197             32.6
2     Brand C  84524         188             34.9
3     Brand E  68939         258             15.1
4     Brand X  66505         277             13.0
...       ...    ...         ...              ...
1995  Brand Z  34535         196             15.2
1996  Brand C  35215         377             25.3
1997  Brand E  72980         294             21.8
1998  Brand Z  55921         443             11.0
1999  Brand B  95051         225             12.4

[2000 rows x 4 columns]

In [95]:
brand_avg_prices=df.groupby('Brand')['Price'].mean().sort_values(ascending=False)
brand_avg_prices

Brand
Brand D    65498.701681
Brand X    65405.884259
Brand Z    65244.331818
Brand C    64707.967890
Brand B    64686.641350
Brand A    64224.495370
Brand Y    63880.171569
Brand E    63712.542601
Brand W    63034.557018
Name: Price, dtype: float64

In [96]:
df.shape

(2000, 4)

In [97]:
# Clean the dataset
df.dropna(inplace=True)

df.shape

(2000, 4)

In [98]:
dfnobrand = df[df['Brand'].isna()]
dfnobrand

Empty DataFrame
Columns: [Brand, Price, Horsepower, Fuel Efficiency]
Index: []

In [99]:
dfnohp = df[df['Horsepower'].isna()]
dfnohp

Empty DataFrame
Columns: [Brand, Price, Horsepower, Fuel Efficiency]
Index: []

In [100]:
dfnoprice = df[df['Price'].isna()]
dfnoprice

Empty DataFrame
Columns: [Brand, Price, Horsepower, Fuel Efficiency]
Index: []

In [101]:
dfnoprice = df[df['Fuel Efficiency'].isna()]
dfnoprice

Empty DataFrame
Columns: [Brand, Price, Horsepower, Fuel Efficiency]
Index: []

In [102]:
brand_avg_prices = df.groupby('Brand')['Price'].mean().sort_values(ascending=False)
brand_avg_prices.count()

np.int64(9)

In [103]:

d={}
for i in brand_avg_prices.index:
  print(i)

Brand D
Brand X
Brand Z
Brand C
Brand B
Brand A
Brand Y
Brand E
Brand W

In [104]:
d = {}
j=len(brand_avg_prices)
for i in brand_avg_prices.index:
  d[i] = j
  j-=1
d

{'Brand D': 9,
 'Brand X': 8,
 'Brand Z': 7,
 'Brand C': 6,
 'Brand B': 5,
 'Brand A': 4,
 'Brand Y': 3,
 'Brand E': 2,
 'Brand W': 1}

In [105]:
x=[]
for j in df['Brand']:
  y=d[j]
  x.append(y)
df['Encoded brand']=x
df

        Brand  Price  Horsepower  Fuel Efficiency  Encoded brand
0     Brand C  91942         382             15.3              6
1     Brand A  70075         197             32.6              4
2     Brand C  84524         188             34.9              6
3     Brand E  68939         258             15.1              2
4     Brand X  66505         277             13.0              8
...       ...    ...         ...              ...            ...
1995  Brand Z  34535         196             15.2              7
1996  Brand C  35215         377             25.3              6
1997  Brand E  72980         294             21.8              2
1998  Brand Z  55921         443             11.0              7
1999  Brand B  95051         225             12.4              5

[2000 rows x 5 columns]

In [106]:
fe=[]
min=df['Fuel Efficiency'].min()
max=df['Fuel Efficiency'].max()
for i in df['Fuel Efficiency']:
  scaled_value=(i-min)/(max-min)
  fe.append(scaled_value)
df['Scaled Fuel efficiency']=fe
df

,Brand,Price,Horsepower,Fuel Efficiency,Encoded brand,Scaled Fuel efficiency
0,Brand C,91942,382,15.3,6,0.212
1,Brand A,70075,197,32.6,4,0.904
2,Brand C,84524,188,34.9,6,0.996
3,Brand E,68939,258,15.1,2,0.204
4,Brand X,66505,277,13.0,8,0.120
...,...,...,...,...,...,...
1995,Brand Z,34535,196,15.2,7,0.208
1996,Brand C,35215,377,25.3,6,0.612
1997,Brand E,72980,294,21.8,2,0.472
1998,Brand Z,55921,443,11.0,7,0.040
1999,Brand B,95051,225,12.4,5,0.096

In [107]:
hp=[]
min=df['Horsepower'].min()
max=df['Horsepower'].max()
for i in df['Horsepower']:
  scaled_value=(i-min)/(max-min)
  hp.append(scaled_value)
df['Scaled Horsepower']=hp
df

,Brand,Price,Horsepower,Fuel Efficiency,Encoded brand,Scaled Fuel efficiency,Scaled Horsepower
0,Brand C,91942,382,15.3,6,0.212,0.7050
1,Brand A,70075,197,32.6,4,0.904,0.2425
2,Brand C,84524,188,34.9,6,0.996,0.2200
3,Brand E,68939,258,15.1,2,0.204,0.3950
4,Brand X,66505,277,13.0,8,0.120,0.4425
...,...,...,...,...,...,...,...
1995,Brand Z,34535,196,15.2,7,0.208,0.2400
1996,Brand C,35215,377,25.3,6,0.612,0.6925
1997,Brand E,72980,294,21.8,2,0.472,0.4850
1998,Brand Z,55921,443,11.0,7,0.040,0.8575
1999,Brand B,95051,225,12.4,5,0.096,0.3125

In [108]:
eb=[]
min=df['Encoded brand'].min()
max=df['Encoded brand'].max()
for i in df['Encoded brand']:
  scaled_value=(i-min)/(max-min)
  eb.append(scaled_value)
df['Scaled Encoded brand']=eb
df

,Brand,Price,Horsepower,Fuel Efficiency,Encoded brand,Scaled Fuel efficiency,Scaled Horsepower,Scaled Encoded brand
0,Brand C,91942,382,15.3,6,0.212,0.7050,0.625
1,Brand A,70075,197,32.6,4,0.904,0.2425,0.375
2,Brand C,84524,188,34.9,6,0.996,0.2200,0.625
3,Brand E,68939,258,15.1,2,0.204,0.3950,0.125
4,Brand X,66505,277,13.0,8,0.120,0.4425,0.875
...,...,...,...,...,...,...,...,...
1995,Brand Z,34535,196,15.2,7,0.208,0.2400,0.750
1996,Brand C,35215,377,25.3,6,0.612,0.6925,0.625
1997,Brand E,72980,294,21.8,2,0.472,0.4850,0.125
1998,Brand Z,55921,443,11.0,7,0.040,0.8575,0.750
1999,Brand B,95051,225,12.4,5,0.096,0.3125,0.500

In [109]:
df['Performance Index']=(df['Horsepower'] * 0.7 + df['Fuel Efficiency'] * 0.3) / df['Price']

In [110]:
df

,Brand,Price,Horsepower,Fuel Efficiency,Encoded brand,Scaled Fuel efficiency,Scaled Horsepower,Scaled Encoded brand,Performance Index
0,Brand C,91942,382,15.3,6,0.212,0.7050,0.625,0.002958
1,Brand A,70075,197,32.6,4,0.904,0.2425,0.375,0.002107
2,Brand C,84524,188,34.9,6,0.996,0.2200,0.625,0.001681
3,Brand E,68939,258,15.1,2,0.204,0.3950,0.125,0.002685
4,Brand X,66505,277,13.0,8,0.120,0.4425,0.875,0.002974
...,...,...,...,...,...,...,...,...,...
1995,Brand Z,34535,196,15.2,7,0.208,0.2400,0.750,0.004105
1996,Brand C,35215,377,25.3,6,0.612,0.6925,0.625,0.007709
1997,Brand E,72980,294,21.8,2,0.472,0.4850,0.125,0.002910
1998,Brand Z,55921,443,11.0,7,0.040,0.8575,0.750,0.005604
1999,Brand B,95051,225,12.4,5,0.096,0.3125,0.500,0.001696

In [111]:
df.to_csv('23AG1A67G5.csv', index=False)